name: NIFTY_500

on:
  schedule:
    - cron: '30 19 * * *'  # 1:00 AM IST
    - cron: '30 0 * * *'   # 6:00 AM IST
    - cron: '30 2 * * *'   # 8:00 AM IST (Default scheduled run)
  workflow_dispatch:
    inputs:
      csv_url:
        description: 'Official CSV URL to fetch'
        required: true
        default: 'https://www.niftyindices.com//IndexConstituent/ind_niftyautolist.csv'
      table_id:
        description: 'Grist Table ID to sync into'
        required: true
        default: 'NIFTY_500'

jobs:
  sync_index:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Fetch CSV and Add Timestamp
      env:
        CSV_URL: ${{ github.event.inputs.csv_url || 'https://www.niftyindices.com/IndexConstituent/ind_nifty50list.csv' }}
      run: |
        echo "Fetching from: $CSV_URL"
        curl -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)" "$CSV_URL" > temp.csv
        CURRENT_TIME=$(env TZ=Asia/Kolkata date "+%Y-%m-%d %H:%M:%S IST")
        awk -v time="$CURRENT_TIME" 'NR==1 {print $0 ",Fetch_Time"} NR>1 {print $0 "," time}' temp.csv > target_list.csv
        rm temp.csv

    - name: Clean Overwrite Sheet & Dynamic Columns Sync