name: Nifty 50 CSV

on:
  schedule:
    - cron: '30 19 * * *'  # 1:00 AM IST
    - cron: '30 0 * * *'   # 6:00 AM IST
    - cron: '30 2 * * *'   # 8:00 AM IST
  workflow_dispatch:

jobs:
  fetch_csv:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Fetch CSV and Add Clean Timestamp
      run: |
        # 1. Pehle original clean file download karo
        curl -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
             "https://www.niftyindices.com/IndexConstituent/ind_nifty50list.csv" > temp.csv
        
        # 2. Live Indian Time nikalna
        CURRENT_TIME=$(env TZ=Asia/Kolkata date "+%Y-%m-%d %H:%M:%S IST")
        
        # 3. Pehli row (Header) ke aage Fetch_Time jodna
        awk -v time="$CURRENT_TIME" 'NR==1 {print $0 ",Fetch_Time"} NR>1 {print $0 "," time}' temp.csv > ind_nifty50list.csv
        
        # 4. Kachra saaf karna
        rm temp.csv
        echo "Clean data generated with timestamp!"

    - name: Commit and Force Push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add ind_nifty50list.csv
        
        git commit -m "Official Nifty 50 CSV Clean Force Updated" || exit 0
        git push origin main --force
